// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc_EyjI8SY7W8C1gpO4YkJRUwvjUtYIrA',
    appId: '1:729827175436:web:201270b8f0d034145a1229',
    messagingSenderId: '729827175436',
    projectId: 'rsvp-22bdf',
    authDomain: 'rsvp-22bdf.firebaseapp.com',
    storageBucket: 'rsvp-22bdf.appspot.com',
    measurementId: 'G-28KHQJE762',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCanGtJ3y2wqMjbrSCV5o5mCf761jSCG70',
    appId: '1:729827175436:android:f540b086aadc42575a1229',
    messagingSenderId: '729827175436',
    projectId: 'rsvp-22bdf',
    storageBucket: 'rsvp-22bdf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf799uQC6NvfI8c2PxKFM4G7IA6u1cDQs',
    appId: '1:729827175436:ios:f288de5f21a1b2e05a1229',
    messagingSenderId: '729827175436',
    projectId: 'rsvp-22bdf',
    storageBucket: 'rsvp-22bdf.appspot.com',
    androidClientId:
        '729827175436-j7ha49c27992635jvfp70i49fp1rc79k.apps.googleusercontent.com',
    iosClientId:
        '729827175436-it85npchu5m9k2slq0uqb42tvodju7rs.apps.googleusercontent.com',
    iosBundleId: 'com.wml.rsvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf799uQC6NvfI8c2PxKFM4G7IA6u1cDQs',
    appId: '1:729827175436:ios:a9fb3d71aef8ffbf5a1229',
    messagingSenderId: '729827175436',
    projectId: 'rsvp-22bdf',
    storageBucket: 'rsvp-22bdf.appspot.com',
    androidClientId:
        '729827175436-j7ha49c27992635jvfp70i49fp1rc79k.apps.googleusercontent.com',
    iosClientId:
        '729827175436-8460vuqj1ei12vkbpa9kt6a31sji2pkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCreate',
  );
}
