// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCanGtJ3y2wqMjbrSCV5o5mCf761jSCG70',
    appId: '1:729827175436:android:f540b086aadc42575a1229',
    messagingSenderId: '729827175436',
    projectId: 'rsvp-22bdf',
    storageBucket: 'rsvp-22bdf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf799uQC6NvfI8c2PxKFM4G7IA6u1cDQs',
    appId: '1:729827175436:ios:5a97bbefba52ac745a1229',
    messagingSenderId: '729827175436',
    projectId: 'rsvp-22bdf',
    storageBucket: 'rsvp-22bdf.appspot.com',
    androidClientId: '729827175436-j7ha49c27992635jvfp70i49fp1rc79k.apps.googleusercontent.com',
    iosClientId: '729827175436-7g2nb0lut0t5fbjnlh8irn5m8bkqjh7i.apps.googleusercontent.com',
    iosBundleId: 'com.wml.rsvpcorsairs',
  );
}
