// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeoO3BACxhCcm8Sq2oGkZR2uRbca6VHRE',
    appId: '1:726058956773:web:7fcbf23d2ea0e1c246610c',
    messagingSenderId: '726058956773',
    projectId: 'vocabhub-34c7f',
    authDomain: 'vocabhub-34c7f.firebaseapp.com',
    storageBucket: 'vocabhub-34c7f.appspot.com',
    measurementId: 'G-PX6FK67F2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0HNRQzSBOg_xM7EhiafasmGKc1ppn9z8',
    appId: '1:726058956773:android:8936f0697afa6bc546610c',
    messagingSenderId: '726058956773',
    projectId: 'vocabhub-34c7f',
    storageBucket: 'vocabhub-34c7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYo7FXd_J3OmBozNGmLTaWlH4tzT_hCJ8',
    appId: '1:726058956773:ios:8a95b2206666c84146610c',
    messagingSenderId: '726058956773',
    projectId: 'vocabhub-34c7f',
    storageBucket: 'vocabhub-34c7f.appspot.com',
    androidClientId: '726058956773-4ne1tc35bt4qqr4r8c2juba5hs1lekrq.apps.googleusercontent.com',
    iosClientId: '726058956773-r2pi1l5jiiglm9bu586hc396k58vqp9u.apps.googleusercontent.com',
    iosBundleId: 'com.vocabhub.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYo7FXd_J3OmBozNGmLTaWlH4tzT_hCJ8',
    appId: '1:726058956773:ios:8a95b2206666c84146610c',
    messagingSenderId: '726058956773',
    projectId: 'vocabhub-34c7f',
    storageBucket: 'vocabhub-34c7f.appspot.com',
    androidClientId: '726058956773-4ne1tc35bt4qqr4r8c2juba5hs1lekrq.apps.googleusercontent.com',
    iosClientId: '726058956773-r2pi1l5jiiglm9bu586hc396k58vqp9u.apps.googleusercontent.com',
    iosBundleId: 'com.vocabhub.app',
  );
}
